#!/usr/bin/env bash
# PostToolUse hook: auto-format .dart files after Edit/Write tool calls.
# Reads the tool call JSON from stdin and formats only Dart files.
INPUT=$(cat)

FILE_PATH=$(echo "$INPUT" | node -e \
  "let d='';process.stdin.on('data',c=>d+=c);process.stdin.on('end',()=>{try{const o=JSON.parse(d);process.stdout.write(o.tool_input?.file_path||'')}catch(e){}})" \
  2>/dev/null)

# Skip non-.dart files silently
[[ "$FILE_PATH" == *.dart ]] || exit 0

# Skip generated files — they're regenerated by build_runner, not hand-edited
[[ "$FILE_PATH" == *.g.dart ]] && exit 0
[[ "$FILE_PATH" == *.freezed.dart ]] && exit 0

dart format "$FILE_PATH" 2>/dev/null
exit 0
